### ISSUE TITLE
remaining task list for modules

### ISSUE THREAD

**Issue by MLHale** [MLHale/nebraska-gencyber-modules#18]
# Priority rank-list of remaining tasks

- [x] 1. Update all links to the latest module names.
- [x] 2. Double check that all links are accurate.
- [x] 3. Modify littlebits intro lesson to use droids instead of IoT kit
- [x] 4. Create Design Process / computational thinking with littlebits lesson
- [x] 5. Modify littlebits IFTTT lesson to use droids instead of IoT kit
- [x] 6. Upload resources from Kristeen and Chris to their respective lesson locations.
- [x] 7. verify pen-testing lesson is functioning as expected on the NGC image
- [x] 8. merge tyler's formatting changes in.
